### ISSUE TITLE
PermissionError: [WinError 5] 拒绝访问。

### ISSUE THREAD

**Issue by Pa55w0rd** [timwhitez/crawlergo_x_XRAY#1]
```
Traceback (most recent call last):
  File "launcher.py", line 80, in <module>
    main(data1)
  File "launcher.py", line 59, in main
    rsp = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "D:\Python38\Lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Python38\Lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] 拒绝访问。
```

**Comment by Pa55w0rd** [comment]
已解决

**Comment by gwjczwy** [comment]
怎么解决的?

**Comment by heiheip** [comment]
你好这是什么原因如何解决-！

**Comment by timwhitez** [comment]
> 你好这是什么原因如何解决-！

删除掉py目录下crawlergo这个文件夹。
