### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by deIndra** [timwhitez/crawlergo_x_XRAY#13]
运行提示FileNotFoundError: [WinError 2] 系统找不到指定的文件。
查了路径是没有问题的
报错信息如下：
Traceback (most recent call last):
  File "launcher.py", line 89, in <module>
    main(data1)
  File "launcher.py", line 59, in main
    rsp = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "H:\python\python3.7\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "H:\python\python3.7\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by timwhitez** [comment]
你看看是不是存在空的crawlergo文件夹没删掉
