### ISSUE TITLE
win7 x64 error

### ISSUE THREAD

**Issue by Mikry-afk** [timwhitez/crawlergo_x_XRAY#3]
C:\Users\Public\crawlergo_x_XRAY>python3 launcher.py
Traceback (most recent call last):
  File "launcher.py", line 83, in <module>
    main(data1)
  File "launcher.py", line 59, in main
    rsp = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)

**Comment by timwhitez** [comment]
这个问题我暂时没有遇到过，不太清楚怎么解决

**Comment by ming-sec** [comment]
已经解决了，注意将64位的crawlergo.exe和launcher.py还有targets.txt放在一个目录，将crawlergo目录给删除即可。。。
