### ISSUE TITLE
PermissionError: [WinError 5] 拒绝访问。

### ISSUE THREAD

**Issue by HeartSleep** [timwhitez/crawlergo_x_XRAY#8]
Traceback (most recent call last):
  File "launcher.py", line 83, in <module>
    main(data1)
  File "launcher.py", line 59, in main
    rsp = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] 拒绝访问。

请问这个情况怎么解决

**Comment by timwhitez** [comment]
删除crawlergo空文件夹即可
